services:
  - type: web
    name: instagram-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: INSTAGRAM_CSRFTOKEN
        sync: false
      - key: INSTAGRAM_SESSIONID
        sync: false
