services:
  - type: web
    name: instagram-downloader-api
    env: python
    runtime: python
    region: oregon
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --threads=4 --timeout=120 --log-level info

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
