services:
  - type: web
    name: instagram-downloader
    env: python
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: INSTAGRAM_CSRFTOKEN
        sync: false
      - key: INSTAGRAM_SESSIONID
        sync: false
